services:
  ai-microservice:
    container_name: ai-microservice
    build: ./server_ai/
    env_file:
      - ./server_ai/.env
    networks:
      - app
  server:
    env_file:
      - ./server/.env
    build: ./server/

networks:
  app:
    driver: bridge
